directories:
  output: release
  buildResources: build
appId: com.ainold.markdown
productName: AinoldMarkdown
files:
  - filter:
      - dist/**/*
      - electron/**/*
      - package.json
asar: true
fileAssociations:
  - ext: md
    name: Markdown Document
    description: Markdown file
    role: Editor
  - ext: markdown
    name: Markdown Document
    description: Markdown file
    role: Editor
win:
  target:
    - nsis
    - portable
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  include: build/installer.nsh
electronVersion: 34.2.0
